name: CI
on: [push, pull_request]
jobs:
    linux-ci:
        name: Linux
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Release
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Debug

                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Release
                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Debug

                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Release
                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Debug

                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Release
                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Debug

                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Release
                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Initialize submodules
            run: |
                git submodule update --init --recursive
          - name: Install dependencies
            run: |
                sudo apt install -y libpython3-dev python3-numpy doxygen
                cd ${{runner.workspace}}

                git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.0
                mkdir SoapySDR/build
                cd SoapySDR/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF ..
                make
                sudo make install
                sudo ldconfig
          - name: Build Pothos and submodules
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
                sudo ldconfig
          - name: Run self tests
            run: |
                cd ${{github.workspace}}/build
                PothosUtil --self-tests
    osx-ci:
        name: OS X
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: clang
                      cxx: clang++
                      build_type: Release
                    - cc: clang
                      cxx: clang++
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Initialize submodules
            run: |
                git submodule update --init --recursive
          - name: Install dependencies
            run: |
                brew install doxygen
                pip3 install numpy

                git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.0
                mkdir SoapySDR/build
                cd SoapySDR/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF ..
                make
                sudo make install
          - name: Build Pothos and submodules
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
          - name: Run self tests
            run: |
                cd ${{github.workspace}}/build
                PothosUtil --self-tests
